# Generated by Django 6.1 on 2026-09-03 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_is_published_online_product_product_type_and_more'),
        ('inventory', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stocklevel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='stocklevel',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.productvariant'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('adjustment', 'Adjustment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('return_in', 'Return In'), ('return_out', 'Return Out'), ('ecommerce_reservation', 'E-commerce Reservation'), ('ecommerce_release', 'E-commerce Release')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='stocklevel',
            unique_together={('product', 'branch', 'variant')},
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['variant', 'branch'], name='inventory_s_variant_062c6d_idx'),
        ),
    ]
