# Generated by Django 6.1 on 2026-09-13 17:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
        ('tenants', '0002_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='is_supplier_reference',
            field=models.BooleanField(default=False, help_text='True if reference_number was supplied by the supplier (their own PO/invoice number) rather than auto-generated.'),
        ),
        migrations.CreateModel(
            name='BranchPurchaseSequence',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_sequence', to='tenants.branch')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
