# backend/apps/purchases/serializers.py

from rest_framework import serializers
from apps.tenants.models import Branch
from .models import Supplier, PurchaseOrder, PurchaseOrderItem


class SupplierSerializer(serializers.ModelSerializer):
    class Meta:
        model = Supplier
        fields = ["id", "name", "phone", "email", "address", "is_active"]


class PurchaseOrderItemSerializer(serializers.ModelSerializer):
    product_sku = serializers.CharField(source="product.sku", read_only=True)
    product_name = serializers.CharField(source="product.name", read_only=True)

    class Meta:
        model = PurchaseOrderItem
        fields = [
            "id", "product", "product_sku", "product_name",
            "quantity_ordered", "quantity_received", "unit_cost",
        ]
        read_only_fields = ["quantity_received"]


class PurchaseOrderSerializer(serializers.ModelSerializer):
    """
    Writable nested serializer: creating a PurchaseOrder also creates its
    line items in the same request — the frontend sends the whole PO
    (header + items) as one payload rather than making N+1 calls.

    branch and reference_number are both optional from the client:
    - branch is inferred from X-Active-Branch by the view's perform_create.
    - reference_number is auto-generated by the view if not supplied.
    Neither is part of a unique_together constraint here, so a plain
    required=False (unlike catalog's organization field) is sufficient —
    no HiddenField trick needed.
    """
    items = PurchaseOrderItemSerializer(many=True)
    supplier_name = serializers.CharField(
        source="supplier.name", read_only=True)
    branch = serializers.PrimaryKeyRelatedField(
        queryset=Branch.objects.all(), required=False)
    reference_number = serializers.CharField(required=False)

    class Meta:
        model = PurchaseOrder
        fields = [
            "id", "branch", "supplier", "supplier_name", "reference_number",
            "status", "order_date", "expected_date", "notes", "items",
        ]
        read_only_fields = ["status"]

    def create(self, validated_data):
        items_data = validated_data.pop("items")
        purchase_order = PurchaseOrder.objects.create(**validated_data)
        for item_data in items_data:
            PurchaseOrderItem.objects.create(
                purchase_order=purchase_order, **item_data)
        return purchase_order
