# Generated by Django 6.1 on 2026-09-05 16:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='home_banners/')),
                ('cta_label', models.CharField(blank=True, default='Shop Now', max_length=50)),
                ('cta_url', models.CharField(blank=True, default='/products', max_length=300)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide immediately without deleting the row.')),
                ('starts_at', models.DateTimeField(blank=True, help_text="Leave blank to show as soon as it's active.", null=True)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Leave blank to keep showing indefinitely.', null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_banners', to='tenants.organization')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
    ]
